sudo: required

language: java

jdk:
  - oraclejdk8

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kalakris-cmake
      - boost-latest
    packages:
      - libcppunit-dev
      - libboost1.55-all-dev
      - libhdf5-serial-dev
      - cmake
      - g++-4.8

install:
  # set compiler
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 100
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 100
  - sudo update-alternatives --config gcc
  - sudo update-alternatives --config g++
  - g++ --version
  # build nix library
  - mkdir nix-build
  - cd nix-build
  - git clone https://github.com/G-Node/nix
  - cd nix
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTING=OFF ..
  - make all
  - sudo make install
  - cd ../../..

script:
  - mvn clean package

